# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# hook_add = '''
#   let g:deoplete#enable_at_startup   = 1
#   let g:deoplete#auto_complete_delay = 0
#   inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
# '''

[[plugins]]
repo ='Shougo/defx.nvim'
on_cmd = 'Defx'
depends = ['defx-icons', 'defx-git']
hook_add = '''
  nnoremap <silent> <Space>f :<C-u>Defx -split=vertical -winwidth=40 -direction=topleft -listed -resume -buffer-name=tab`tabpagenr()`<CR>
'''
hook_source = '''
  function! Root(path) abort
    return fnamemodify(a:path, ':t')
  endfunction
  call defx#custom#source('file', {
      \ 'root': 'Root',
      \})
  call defx#custom#column('filename', {
      \ 'directory_icon': '+',
      \ 'opened_icon': '-'
      \ })
  call defx#custom#column('mark', {
      \ 'readonly_icon': '[ro]',
      \ 'selected_icon': '->'
      \ })
  call defx#custom#option('_', {
      \ 'columns': 'indent:git:icons:filename',
      \ 'show_ignored_files': 1,
      \ })
'''

[plugins.ftplugin]
defx = '''
  source ~/.config/nvim/plugins/defx-keymap.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo ='kristijanhusak/defx-git'
hook_add = '''
  let g:defx_git#indicators = {
    \ 'Modified'  : '+',
    \ 'Staged'    : '●',
    \ 'Untracked' : '?',
    \ 'Renamed'   : '➜',
    \ 'Unmerged'  : '═',
    \ 'Deleted'   : 'x',
    \ 'Unknown'   : '?'
    \ }
'''

